baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Test site for mod-hubspot'

[module]
  # Build and serve using local mod-hubspot clone declared in the named Hugo workspace:
  workspace = "mod-hubspot.work"
  [[module.mounts]]
    source = "content"
    target = "content"
  [[module.mounts]]
    source = "data"
    target = "data"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.imports]]
    path = "github.com/gethinode/mod-hubspot"
  [[module.imports.mounts]]
    source = "assets/js/modules/hubspot/hubspot.js"
    target = "assets/js/hubspot.js"
  [[module.imports.mounts]]
    source = "data"
    target = "data"
  [[module.imports.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.imports]]
    path = "github.com/gethinode/mod-utils/v2"
