name: PR auto-merge
on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    uses: gethinode/.github/.github/workflows/auto-merge.yml@v1
    secrets: inherit
